#  docker build -t beagle/sinaspider:1.0 -f Dockerfile  .
FROM beagle/centos-python-pip-mongo:2.7.5
MAINTAINER xjw <xingjw@beagledata.com>
RUN pip  install requests \
&& pip  install scrapy \
&& pip  install  pymongo 


